
aws:
  upload: true
  bucket_name: klt1102-bucket
  prefix: experiments/{run_config.name}
  model_file_keys:
    model1: v1.pkl
    model2: v2.pkl
  data_file_key: clouds.csv
  region_name: 'us-east-1'
